version: "3.7"
services:
  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - /Users/rafiq/Code/jupyter:/home/jovyan/work
      - /Users/rafiq/Dropbox/Music:/home/jovyan/music:ro
    ports:
      - "8888:8888"
    networks:
      - jupyternet
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - jupyternet

networks:
  jupyternet:
    driver: "bridge"